// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250409040357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            LecturerName = "M.M. Herath",
                            Name = "Web Development"
                        },
                        new
                        {
                            CourseId = 2,
                            LecturerName = "J.S.V. Piyasena",
                            Name = "Graphic Design"
                        },
                        new
                        {
                            CourseId = 3,
                            LecturerName = "K.K.S. Dias",
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            CourseId = 4,
                            LecturerName = "U.H.S. Perera",
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            City = "Kandy",
                            CourseId = 2,
                            Name = "Kasun Gamage"
                        },
                        new
                        {
                            StudentId = 2,
                            City = "Jaffna",
                            CourseId = 3,
                            Name = "Daniel Sam"
                        },
                        new
                        {
                            StudentId = 3,
                            City = "Colombo",
                            CourseId = 1,
                            Name = "Hansi Silva"
                        },
                        new
                        {
                            StudentId = 4,
                            City = "Matara",
                            CourseId = 3,
                            Name = "Ranidu Heath"
                        },
                        new
                        {
                            StudentId = 5,
                            City = "Kandy",
                            CourseId = 4,
                            Name = "Praneeth Wijesinghe"
                        },
                        new
                        {
                            StudentId = 6,
                            City = "Rathnapura",
                            CourseId = 1,
                            Name = "Nuwani Herath"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
